FROM arm64v8/python:3.7-slim-buster

WORKDIR /app
RUN apt-get update
RUN apt-get -y install apt-utils
RUN apt-get -y install gcc
RUN apt-get -y install libffi-dev
RUN apt-get -y install libssl-dev
COPY requirements.txt ./
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]